export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREMENT_CARD_ITEM = "INCREMENT_CARD_ITEM";
export const DECREMENT_CARD_ITEM = "DECREMENT_CARD_ITEM";
